package Calculator;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;

/**
 * @author : ARDLMNT
 * Created on: 10/28/2016
 * P.S It's not yet fully fixed. Maraming flaws, hasol gamiton. One by one ra siya maka perform ug operations. Sad Life :(
 * 
 */



@SuppressWarnings("serial")
public class Calculator extends javax.swing.JFrame {

	    public javax.swing.JPanel charCharSaDisplay;
	    public javax.swing.JButton clearButton;
	    public javax.swing.JButton decimalButton;
	    public javax.swing.JPanel displayBackground;
	    public javax.swing.JTextField displayField;
	    public javax.swing.JPanel displayMargin;
	    public javax.swing.JButton divideButton;
	    public javax.swing.JButton eightButton;
	    public javax.swing.JButton fiveButton;
	    public javax.swing.JButton fourButton;
	    public javax.swing.JPanel jPanel1;
	    public javax.swing.JPanel jPanel2;
	    public javax.swing.JPanel jPanel3;
	    public javax.swing.JPanel jPanel4;
	    public javax.swing.JPanel jPanel5;
	    public javax.swing.JToolBar jToolBar1;
	    public javax.swing.JPanel keyBG;
	    public javax.swing.JPanel mainBackground;
	    public javax.swing.JButton minusButton;
	    public javax.swing.JButton nineButton;
	    public javax.swing.JPanel numKeyBG;
	    public javax.swing.JPanel numKeyBG1;
	    public javax.swing.JPanel numKeyBG10;
	    public javax.swing.JPanel numKeyBG11;
	    public javax.swing.JPanel numKeyBG2;
	    public javax.swing.JPanel numKeyBG3;
	    public javax.swing.JPanel numKeyBG4;
	    public javax.swing.JPanel numKeyBG5;
	    public javax.swing.JPanel numKeyBG7;
	    public javax.swing.JPanel numKeyBG8;
	    public javax.swing.JPanel numKeyBG9;
	    public javax.swing.JPanel numberKeysBG;
	    public javax.swing.JButton oneButton;
	    public javax.swing.JPanel operations;
	    public javax.swing.JPanel operations1;
	    public javax.swing.JPanel operations2;
	    public javax.swing.JPanel operations3;
	    public javax.swing.JPanel operations5;
	    public javax.swing.JButton percentButton;
	    public javax.swing.JButton plusButton;
	    public javax.swing.JButton sevenButton;
	    public javax.swing.JButton signButton;
	    public javax.swing.JButton sixButton;
	    public javax.swing.JButton threeButton;
	    public javax.swing.JButton timesButton;
	    public javax.swing.JButton totalsButton;
	    public javax.swing.JButton twoButton;
	    public javax.swing.JButton zeroButton;
	    public BigDecimal number1 = BigDecimal.ZERO;
	    public BigDecimal number2 = BigDecimal.ZERO;
	    public BigDecimal answer = BigDecimal.ZERO;
	    public boolean endOfNumber = false;
	    public boolean decimalState = false;
	    public boolean negative = false;
	    public String operator = "";
	    
          /**
           * Creates new form Calculator
           */
          public Calculator() {
          	setResizable(false);
                    initComponents();
          }

          /**
           * This method is called from within the constructor to initialize the
           * form. WARNING: Do NOT modify this code. The content of this method
           * is always regenerated by the Form Editor.
           */
                                  
          private void initComponents() {
        	  	
                    jToolBar1 = new javax.swing.JToolBar();
                    mainBackground = new javax.swing.JPanel();
                    displayBackground = new javax.swing.JPanel();
                    displayMargin = new javax.swing.JPanel();
                    charCharSaDisplay = new javax.swing.JPanel();
                    displayField = new javax.swing.JTextField("0");
                    keyBG = new javax.swing.JPanel();
                    numberKeysBG = new javax.swing.JPanel();
                    numKeyBG = new javax.swing.JPanel();
                    zeroButton = new javax.swing.JButton();
                    numKeyBG2 = new javax.swing.JPanel();
                    oneButton = new javax.swing.JButton();
                    numKeyBG3 = new javax.swing.JPanel();
                    twoButton = new javax.swing.JButton();
                    numKeyBG4 = new javax.swing.JPanel();
                    threeButton = new javax.swing.JButton();
                    numKeyBG5 = new javax.swing.JPanel();
                    sixButton = new javax.swing.JButton();
                    numKeyBG7 = new javax.swing.JPanel();
                    fiveButton = new javax.swing.JButton();
                    numKeyBG8 = new javax.swing.JPanel();
                    sevenButton = new javax.swing.JButton();
                    numKeyBG9 = new javax.swing.JPanel();
                    fourButton = new javax.swing.JButton();
                    numKeyBG10 = new javax.swing.JPanel();
                    eightButton = new javax.swing.JButton();
                    numKeyBG11 = new javax.swing.JPanel();
                    nineButton = new javax.swing.JButton();
                    numKeyBG1 = new javax.swing.JPanel();
                    decimalButton = new javax.swing.JButton();
                    jPanel1 = new javax.swing.JPanel();
                    operations = new javax.swing.JPanel();
                    totalsButton = new javax.swing.JButton();
                    operations1 = new javax.swing.JPanel();
                    plusButton = new javax.swing.JButton();
                    operations5 = new javax.swing.JPanel();
                    minusButton = new javax.swing.JButton();
                    operations2 = new javax.swing.JPanel();
                    divideButton = new javax.swing.JButton();
                    operations3 = new javax.swing.JPanel();
                    timesButton = new javax.swing.JButton();
                    jPanel2 = new javax.swing.JPanel();
                    jPanel5 = new javax.swing.JPanel();
                    signButton = new javax.swing.JButton();
                    jPanel3 = new javax.swing.JPanel();
                    percentButton = new javax.swing.JButton();
                    jPanel4 = new javax.swing.JPanel();
                    clearButton = new javax.swing.JButton();

                    jToolBar1.setRollover(true);

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setTitle("Calculator");

                    mainBackground.setBackground(new java.awt.Color(0, 0, 0));

                    displayBackground.setBackground(new java.awt.Color(0, 0, 10));
                    displayBackground.setForeground(new java.awt.Color(0, 0, 10));

                    displayMargin.setBackground(new java.awt.Color(0, 0, 23));
                    displayMargin.setBorder(javax.swing.BorderFactory.createEtchedBorder());

                    charCharSaDisplay.setBackground(new java.awt.Color(0, 11, 49));
                    charCharSaDisplay.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                    displayField.setEditable(false);
                    displayField.setBackground(new java.awt.Color(0, 11, 49));
                    displayField.setFont(new java.awt.Font("Microsoft JhengHei", 0, 25)); // NOI18N
                    displayField.setForeground(new java.awt.Color(255, 255, 255));
                    displayField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
                    displayField.setBorder(null);
                    displayField.setCaretColor(new java.awt.Color(204, 204, 204));
                    displayField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
                    displayField.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
                    displayField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
                    displayField.setOpaque(false);
                    displayField.setRequestFocusEnabled(false);
                    
                    javax.swing.GroupLayout charCharSaDisplayLayout = new javax.swing.GroupLayout(charCharSaDisplay);
                    charCharSaDisplay.setLayout(charCharSaDisplayLayout);
                    charCharSaDisplayLayout.setHorizontalGroup(
                              charCharSaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(charCharSaDisplayLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(displayField)
                                        .addContainerGap())
                    );
                    charCharSaDisplayLayout.setVerticalGroup(
                              charCharSaDisplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(charCharSaDisplayLayout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(displayField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(14, Short.MAX_VALUE))
                    );

                    javax.swing.GroupLayout displayMarginLayout = new javax.swing.GroupLayout(displayMargin);
                    displayMargin.setLayout(displayMarginLayout);
                    displayMarginLayout.setHorizontalGroup(
                              displayMarginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(displayMarginLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(charCharSaDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                    );
                    displayMarginLayout.setVerticalGroup(
                              displayMarginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, displayMarginLayout.createSequentialGroup()
                                        .addContainerGap(17, Short.MAX_VALUE)
                                        .addComponent(charCharSaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                    );

                    javax.swing.GroupLayout displayBackgroundLayout = new javax.swing.GroupLayout(displayBackground);
                    displayBackground.setLayout(displayBackgroundLayout);
                    displayBackgroundLayout.setHorizontalGroup(
                              displayBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(displayBackgroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(displayMargin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                    );
                    displayBackgroundLayout.setVerticalGroup(
                              displayBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(displayBackgroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(displayMargin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    keyBG.setBackground(new java.awt.Color(0, 0, 10));
                    keyBG.setBorder(javax.swing.BorderFactory.createEtchedBorder());
                    keyBG.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

                    numberKeysBG.setBackground(new java.awt.Color(0, 0, 23));

                    numKeyBG.setBackground(new java.awt.Color(0, 11, 50));

                    zeroButton.setBackground(new java.awt.Color(0, 0, 10));
                    zeroButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    zeroButton.setForeground(new java.awt.Color(204, 204, 204));
                    zeroButton.setText("0");
                    zeroButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    zeroButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBGLayout = new javax.swing.GroupLayout(numKeyBG);
                    numKeyBG.setLayout(numKeyBGLayout);
                    numKeyBGLayout.setHorizontalGroup(
                              numKeyBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(zeroButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    numKeyBGLayout.setVerticalGroup(
                              numKeyBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(zeroButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG2.setBackground(new java.awt.Color(0, 11, 50));

                    oneButton.setBackground(new java.awt.Color(0, 0, 10));
                    oneButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    oneButton.setForeground(new java.awt.Color(204, 204, 204));
                    oneButton.setText("1");
                    oneButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    oneButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG2Layout = new javax.swing.GroupLayout(numKeyBG2);
                    numKeyBG2.setLayout(numKeyBG2Layout);
                    numKeyBG2Layout.setHorizontalGroup(
                              numKeyBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(oneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );
                    numKeyBG2Layout.setVerticalGroup(
                              numKeyBG2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(oneButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );

                    numKeyBG3.setBackground(new java.awt.Color(0, 11, 50));

                    twoButton.setBackground(new java.awt.Color(0, 0, 10));
                    twoButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    twoButton.setForeground(new java.awt.Color(204, 204, 204));
                    twoButton.setText("2");
                    twoButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    twoButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG3Layout = new javax.swing.GroupLayout(numKeyBG3);
                    numKeyBG3.setLayout(numKeyBG3Layout);
                    numKeyBG3Layout.setHorizontalGroup(
                              numKeyBG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(twoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );
                    numKeyBG3Layout.setVerticalGroup(
                              numKeyBG3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(twoButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );

                    numKeyBG4.setBackground(new java.awt.Color(0, 11, 50));

                    threeButton.setBackground(new java.awt.Color(0, 0, 10));
                    threeButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    threeButton.setForeground(new java.awt.Color(204, 204, 204));
                    threeButton.setText("3");
                    threeButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    threeButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG4Layout = new javax.swing.GroupLayout(numKeyBG4);
                    numKeyBG4.setLayout(numKeyBG4Layout);
                    numKeyBG4Layout.setHorizontalGroup(
                              numKeyBG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(threeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );
                    numKeyBG4Layout.setVerticalGroup(
                              numKeyBG4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(threeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );

                    numKeyBG5.setBackground(new java.awt.Color(0, 11, 50));

                    sixButton.setBackground(new java.awt.Color(0, 0, 10));
                    sixButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    sixButton.setForeground(new java.awt.Color(204, 204, 204));
                    sixButton.setText("6");
                    sixButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    sixButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG5Layout = new javax.swing.GroupLayout(numKeyBG5);
                    numKeyBG5.setLayout(numKeyBG5Layout);
                    numKeyBG5Layout.setHorizontalGroup(
                              numKeyBG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(sixButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG5Layout.setVerticalGroup(
                              numKeyBG5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(sixButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG7.setBackground(new java.awt.Color(0, 11, 50));

                    fiveButton.setBackground(new java.awt.Color(0, 0, 10));
                    fiveButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    fiveButton.setForeground(new java.awt.Color(204, 204, 204));
                    fiveButton.setText("5");
                    fiveButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    fiveButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG7Layout = new javax.swing.GroupLayout(numKeyBG7);
                    numKeyBG7.setLayout(numKeyBG7Layout);
                    numKeyBG7Layout.setHorizontalGroup(
                              numKeyBG7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(fiveButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG7Layout.setVerticalGroup(
                              numKeyBG7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(fiveButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG8.setBackground(new java.awt.Color(0, 11, 50));

                    sevenButton.setBackground(new java.awt.Color(0, 0, 10));
                    sevenButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    sevenButton.setForeground(new java.awt.Color(204, 204, 204));
                    sevenButton.setText("7");
                    sevenButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    sevenButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG8Layout = new javax.swing.GroupLayout(numKeyBG8);
                    numKeyBG8.setLayout(numKeyBG8Layout);
                    numKeyBG8Layout.setHorizontalGroup(
                              numKeyBG8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(sevenButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG8Layout.setVerticalGroup(
                              numKeyBG8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(sevenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG9.setBackground(new java.awt.Color(0, 11, 50));

                    fourButton.setBackground(new java.awt.Color(0, 0, 10));
                    fourButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    fourButton.setForeground(new java.awt.Color(204, 204, 204));
                    fourButton.setText("4");
                    fourButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    fourButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG9Layout = new javax.swing.GroupLayout(numKeyBG9);
                    numKeyBG9.setLayout(numKeyBG9Layout);
                    numKeyBG9Layout.setHorizontalGroup(
                              numKeyBG9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(fourButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG9Layout.setVerticalGroup(
                              numKeyBG9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(fourButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG10.setBackground(new java.awt.Color(0, 11, 50));

                    eightButton.setBackground(new java.awt.Color(0, 0, 10));
                    eightButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    eightButton.setForeground(new java.awt.Color(204, 204, 204));
                    eightButton.setText("8");
                    eightButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    eightButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG10Layout = new javax.swing.GroupLayout(numKeyBG10);
                    numKeyBG10.setLayout(numKeyBG10Layout);
                    numKeyBG10Layout.setHorizontalGroup(
                              numKeyBG10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(eightButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG10Layout.setVerticalGroup(
                              numKeyBG10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(eightButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG11.setBackground(new java.awt.Color(0, 11, 50));

                    nineButton.setBackground(new java.awt.Color(0, 0, 10));
                    nineButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    nineButton.setForeground(new java.awt.Color(204, 204, 204));
                    nineButton.setText("9");
                    nineButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    nineButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG11Layout = new javax.swing.GroupLayout(numKeyBG11);
                    numKeyBG11.setLayout(numKeyBG11Layout);
                    numKeyBG11Layout.setHorizontalGroup(
                              numKeyBG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(nineButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG11Layout.setVerticalGroup(
                              numKeyBG11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(nineButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );

                    numKeyBG1.setBackground(new java.awt.Color(0, 11, 50));

                    decimalButton.setBackground(new java.awt.Color(0, 0, 10));
                    decimalButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    decimalButton.setForeground(new java.awt.Color(204, 204, 204));
                    decimalButton.setText(".");
                    decimalButton.setActionCommand("zeroButton");
                    decimalButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    decimalButton.setFocusable(false);

                    javax.swing.GroupLayout numKeyBG1Layout = new javax.swing.GroupLayout(numKeyBG1);
                    numKeyBG1.setLayout(numKeyBG1Layout);
                    numKeyBG1Layout.setHorizontalGroup(
                              numKeyBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(decimalButton, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    );
                    numKeyBG1Layout.setVerticalGroup(
                              numKeyBG1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(decimalButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );
                    
                    oneButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("1");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "1");
 							}
 						}
 					});
                     
                     twoButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("2");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "2");
 							}
 						}
                     });
                     
                     threeButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("3");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "3");
 							}
 						}
                     });
                     
                     fourButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("4");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "4");
 							}
 						}
                     });
                     
                     fiveButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("5");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "5");
 							}
 						}
                     });
                     
                     sixButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("6");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "6");
 							}
 						}
                     });
                     
                     sevenButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("7");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "7");
 							}
 						}
                     });
                     
                     eightButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("8");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							} 							
 							else {
 								displayField.setText(displayField.getText() + "8");
 							}
 						}
                     });
                     
                     nineButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("9");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								displayField.setText(displayField.getText() + "9");
 							}
 						}
                     });
                     
                     decimalButton.addActionListener(new ActionListener() {
 						@Override
 						public void actionPerformed(ActionEvent arg0) {
 							if(displayField.getText().equals("0") || (endOfNumber == true)) {
 								displayField.setText("0.");
 								if(endOfNumber == true) {
 									endOfNumber = false;
 								}
 							}
 							else if(displayField.getText().length() >= 18) {
 								displayField.setText(displayField.getText());
 							}
 							else {
 								if(decimalState == false) {
 	 								displayField.setText(displayField.getText() + ".");
 								} 							}
 							decimalState = true;
 						}
                     });
                     
                     zeroButton.addActionListener(new ActionListener() {
  						@Override
  						public void actionPerformed(ActionEvent arg0) {
  							if(displayField.getText().equals("0") || (endOfNumber == true)) {
  								displayField.setText("0");
  							}
  							else if(displayField.getText().length() >= 18) {
  								displayField.setText(displayField.getText());
  							}
  							else {
  								displayField.setText(displayField.getText() + "0");
  							}
  						}
                      });
                     
                    

                    javax.swing.GroupLayout numberKeysBGLayout = new javax.swing.GroupLayout(numberKeysBG);
                    numberKeysBG.setLayout(numberKeysBGLayout);
                    numberKeysBGLayout.setHorizontalGroup(
                              numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(numberKeysBGLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(numberKeysBGLayout.createSequentialGroup()
                                                            .addComponent(numKeyBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(numKeyBG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(numberKeysBGLayout.createSequentialGroup()
                                                            .addGroup(numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                      .addGroup(numberKeysBGLayout.createSequentialGroup()
                                                                                .addComponent(numKeyBG8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(numKeyBG10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(numKeyBG11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                      .addGroup(numberKeysBGLayout.createSequentialGroup()
                                                                                .addComponent(numKeyBG9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(numKeyBG7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(numKeyBG5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                      .addGroup(numberKeysBGLayout.createSequentialGroup()
                                                                                .addComponent(numKeyBG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(numKeyBG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(numKeyBG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGap(0, 0, Short.MAX_VALUE)))
                                        .addContainerGap())
                    );
                    numberKeysBGLayout.setVerticalGroup(
                              numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, numberKeysBGLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(numKeyBG10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(numKeyBG9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(numKeyBG2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(numberKeysBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addComponent(numKeyBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                  .addComponent(numKeyBG1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    jPanel1.setBackground(new java.awt.Color(0, 25, 33));

                    operations.setBackground(new java.awt.Color(0, 51, 30));

                    totalsButton.setBackground(new java.awt.Color(0, 51, 30));
                    totalsButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    totalsButton.setForeground(new java.awt.Color(255, 255, 255));
                    totalsButton.setText("=");
                    totalsButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(0, 51, 51), null, null));
                    totalsButton.setFocusable(false);

                    javax.swing.GroupLayout operationsLayout = new javax.swing.GroupLayout(operations);
                    operations.setLayout(operationsLayout);
                    operationsLayout.setHorizontalGroup(
                              operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(totalsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    );
                    operationsLayout.setVerticalGroup(
                              operationsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(totalsButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    );
                    
                    
                    operations1.setBackground(new java.awt.Color(0, 51, 51));

                    plusButton.setBackground(new java.awt.Color(0, 0, 5));
                    plusButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    plusButton.setForeground(new java.awt.Color(204, 204, 204));
                    plusButton.setText("+");
                    plusButton.setActionCommand("zeroButton");
                    plusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    plusButton.setFocusable(false);

                    javax.swing.GroupLayout operations1Layout = new javax.swing.GroupLayout(operations1);
                    operations1.setLayout(operations1Layout);
                    operations1Layout.setHorizontalGroup(
                              operations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(plusButton, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    );
                    operations1Layout.setVerticalGroup(
                              operations1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(plusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    );

                    operations5.setBackground(new java.awt.Color(0, 51, 51));

                    minusButton.setBackground(new java.awt.Color(0, 0, 5));
                    minusButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    minusButton.setForeground(new java.awt.Color(204, 204, 204));
                    minusButton.setText("-");
                    minusButton.setActionCommand("zeroButton");
                    minusButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    minusButton.setFocusable(false);

                    javax.swing.GroupLayout operations5Layout = new javax.swing.GroupLayout(operations5);
                    operations5.setLayout(operations5Layout);
                    operations5Layout.setHorizontalGroup(
                              operations5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(minusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    operations5Layout.setVerticalGroup(
                              operations5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(minusButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    );

                    operations2.setBackground(new java.awt.Color(0, 51, 51));

                    divideButton.setBackground(new java.awt.Color(0, 0, 5));
                    divideButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    divideButton.setForeground(new java.awt.Color(204, 204, 204));
                    divideButton.setText("÷");
                    divideButton.setActionCommand("zeroButton");
                    divideButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    divideButton.setFocusable(false);

                    javax.swing.GroupLayout operations2Layout = new javax.swing.GroupLayout(operations2);
                    operations2.setLayout(operations2Layout);
                    operations2Layout.setHorizontalGroup(
                              operations2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(divideButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    operations2Layout.setVerticalGroup(
                              operations2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(divideButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    );

                    operations3.setBackground(new java.awt.Color(0, 51, 51));

                    timesButton.setBackground(new java.awt.Color(0, 0, 5));
                    timesButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    timesButton.setForeground(new java.awt.Color(204, 204, 204));
                    timesButton.setText("*");
                    timesButton.setToolTipText("");
                    timesButton.setActionCommand("zeroButton");
                    timesButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    timesButton.setFocusable(false);
                    
                    totalsButton.addActionListener(new ActionListener() {
						@Override
						public void actionPerformed(ActionEvent arg0) {
							number2 = new BigDecimal(displayField.getText());
							if(!(operator.equals("/"))) {
								if(operator.equals("+")) {
									answer = number1.add(number2);
								}
								if(operator.equals("-")) {
									answer = number1.subtract(number2);
								}
								if(operator.equals("*")) {
									answer = number1.multiply(number2);
								}
								displayField.setText(answer.toString());
							}
							else {
								if(number2.equals("0")) {
									displayField.setText("ERR");
									answer = BigDecimal.ZERO;
									number1 = BigDecimal.ZERO;
								}
								else {
									answer = number1.divide(number2, BigDecimal.ROUND_CEILING);
									displayField.setText(answer.toString());
								}
							}
							operator = "=";
						}
                    });

                    
                    plusButton.addActionListener(new ActionListener() {
                    	@Override
						public void actionPerformed(ActionEvent arg0) {
                    		endOfNumber = true;
							decimalState = false;
							negative = false;
							operator = "+";
							number1 = new BigDecimal(displayField.getText());
                    	}
                    });
                    
                    minusButton.addActionListener(new ActionListener() {
                    	@Override
						public void actionPerformed(ActionEvent arg0) {
                    		endOfNumber = true;
							decimalState = false;
							negative = false;
							operator = "-";
							number1 = new BigDecimal(displayField.getText());
						}
                    	
                    });
                    
                    divideButton.addActionListener(new ActionListener() {
                    	@Override
						public void actionPerformed(ActionEvent arg0) {
                    		endOfNumber = true;
							decimalState = false;
							negative = false;
							operator = "/";
							number1 = new BigDecimal(displayField.getText());
						}
                    });
                    
                    timesButton.addActionListener(new ActionListener() {
                    	@Override
						public void actionPerformed(ActionEvent arg0) {
                    		endOfNumber = true;
							decimalState = false;
							negative = false;
							operator = "*";
							number1 = new BigDecimal(displayField.getText());
                    	}
                    });

                    javax.swing.GroupLayout operations3Layout = new javax.swing.GroupLayout(operations3);
                    operations3.setLayout(operations3Layout);
                    operations3Layout.setHorizontalGroup(
                              operations3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(timesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    operations3Layout.setVerticalGroup(
                              operations3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(timesButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    );

                    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                    jPanel1.setLayout(jPanel1Layout);
                    jPanel1Layout.setHorizontalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                  .addGroup(jPanel1Layout.createSequentialGroup()
                                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                      .addComponent(operations1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                      .addComponent(operations, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                      .addComponent(operations5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                      .addComponent(operations2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                            .addGap(0, 0, Short.MAX_VALUE))
                                                  .addComponent(operations3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap())
                    );
                    jPanel1Layout.setVerticalGroup(
                              jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(operations3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operations2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operations5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operations1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(operations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())
                    );

                    jPanel2.setBackground(new java.awt.Color(8, 11, 41));

                    jPanel5.setBackground(new java.awt.Color(12, 29, 38));

                    signButton.setBackground(new java.awt.Color(0, 0, 10));
                    signButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 24)); // NOI18N
                    signButton.setForeground(new java.awt.Color(204, 204, 204));
                    signButton.setText("+/-");
                    signButton.setActionCommand("zeroButton");
                    signButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    signButton.setFocusable(false);
                    signButton.setOpaque(false);

                    javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
                    jPanel5.setLayout(jPanel5Layout);
                    jPanel5Layout.setHorizontalGroup(
                              jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(signButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    );
                    jPanel5Layout.setVerticalGroup(
                              jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(signButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );

                    jPanel3.setBackground(new java.awt.Color(12, 29, 38));

                    percentButton.setBackground(new java.awt.Color(0, 0, 10));
                    percentButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
                    percentButton.setForeground(new java.awt.Color(204, 204, 204));
                    percentButton.setText("%");
                    percentButton.setActionCommand("zeroButton");
                    percentButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    percentButton.setFocusable(false);

                    javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                    jPanel3.setLayout(jPanel3Layout);
                    jPanel3Layout.setHorizontalGroup(
                              jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(percentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                    );
                    jPanel3Layout.setVerticalGroup(
                              jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(percentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    );

                    jPanel4.setBackground(new java.awt.Color(12, 29, 38));

                    clearButton.setBackground(new java.awt.Color(21, 0, 10));
                    clearButton.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
                    clearButton.setForeground(new java.awt.Color(204, 204, 204));
                    clearButton.setText("AC");
                    clearButton.setActionCommand("zeroButton");
                    clearButton.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
                    clearButton.setFocusable(false);
                    
                    clearButton.addActionListener(new ActionListener() {
						@Override
						public void actionPerformed(ActionEvent e) {
							if(displayField.getText().length() > 1 && !operator.equals("=")) {
								displayField.setText(displayField.getText().substring(0, displayField.getText().length() - 1));
							}
							else if(displayField.getText().length() == 1 && !operator.equals("=")) {
								displayField.setText("0");
							}
							else if(displayField.getText().equals("0") || operator.equals("=")) {
								number1 = BigDecimal.ZERO;
								number2 = BigDecimal.ZERO;
								answer = BigDecimal.ZERO;
								endOfNumber = false;
								displayField.setText("0");
							}
                    	}
                    });
                    
                    percentButton.addActionListener(new ActionListener() {
                    	@Override
						public void actionPerformed(ActionEvent arg0) {
                    		endOfNumber = true;
                    		BigDecimal percentage = number1.multiply(new BigDecimal(displayField.getText()));
                    		BigDecimal ans = percentage.divide(new BigDecimal(100));
                    		displayField.setText(ans.toString());
						}
                    });
                    
                    signButton.addActionListener(new ActionListener() {
						@Override
						public void actionPerformed(ActionEvent e) {
							if(negative == false) {
								endOfNumber = false;
								displayField.setText("-" + displayField.getText());
								negative = true;
							}
							else if(negative == true) {
								displayField.setText(displayField.getText().substring(1));
								negative = false;
							}
							
						}
                    });

                    javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                    jPanel4.setLayout(jPanel4Layout);
                    jPanel4Layout.setHorizontalGroup(
                              jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    jPanel4Layout.setVerticalGroup(
                              jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(clearButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );

                    javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                    jPanel2.setLayout(jPanel2Layout);
                    jPanel2Layout.setHorizontalGroup(
                              jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                    );
                    jPanel2Layout.setVerticalGroup(
                              jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    javax.swing.GroupLayout keyBGLayout = new javax.swing.GroupLayout(keyBG);
                    keyBG.setLayout(keyBGLayout);
                    keyBGLayout.setHorizontalGroup(
                              keyBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(keyBGLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(keyBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                  .addComponent(numberKeysBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                    );
                    keyBGLayout.setVerticalGroup(
                              keyBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, keyBGLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(keyBGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                  .addGroup(keyBGLayout.createSequentialGroup()
                                                            .addGap(0, 1, Short.MAX_VALUE)
                                                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                  .addGroup(keyBGLayout.createSequentialGroup()
                                                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                            .addComponent(numberKeysBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addContainerGap())
                    );

                    javax.swing.GroupLayout mainBackgroundLayout = new javax.swing.GroupLayout(mainBackground);
                    mainBackground.setLayout(mainBackgroundLayout);
                    mainBackgroundLayout.setHorizontalGroup(
                              mainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(mainBackgroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(keyBG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addContainerGap())
                              .addComponent(displayBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    mainBackgroundLayout.setVerticalGroup(
                              mainBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(mainBackgroundLayout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(displayBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(keyBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    );

                    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                    getContentPane().setLayout(layout);
                    layout.setHorizontalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(mainBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    );
                    layout.setVerticalGroup(
                              layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(mainBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    );
                    
                    
                    pack();
          }


          public static void main(String args[]) {
        	  
                    try {
                              for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                                        if ("Nimbus".equals(info.getName())) {
                                                  javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                                  break;
                                        }
                              }
                    } catch (ClassNotFoundException ex) {
                              java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (InstantiationException ex) {
                              java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (IllegalAccessException ex) {
                              java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                              java.util.logging.Logger.getLogger(Calculator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                    }
                    //</editor-fold>

                    /* Create and display the form */
                    java.awt.EventQueue.invokeLater(new Runnable() {
                              public void run() {
                                        new Calculator().setVisible(true);
                              }
                    });
          }
          

          // Variables declaration - do not modify                     

          
          // End of variables declaration                   
}
